conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns=[
    path ('new/<int:item_pk>/', views.new_conversation, name = 'new'),
    path ('<int:pk>/', views.detail, name = 'detail'),
    
    path('', views.inbox, name= 'inbox' ),
    
    
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name ='core'

urlpatterns = [
    path('',views.index, name='index'),
   path('contact/', views.contact, name='contact'),
   path('signup/', views.signup, name='signup'),
   path ('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name = 'login' ),
   
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns =[
    path ('',views.index, name='index'),
]

item/urls.py
from django.urls import path
from . import views

app_name ='item'

urlpatterns = [
    path ('<int:pk>/', views.detail, name='detail'),
    path ('<int:pk>/delete', views.delete, name='delete'),
    path ('<int:pk>/edit', views.edit, name='edit'),
    path ('', views.items, name='items'),
    
    
    path('new/',views.new, name='new'),
]

soko/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),        
    path('admin/', admin.site.urls),
    path('inbox/',include('conversation.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class LoginForm (AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-3/4 py-4 px-6 rounded-xl'
    }))
    
    
     password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-3/4 py-4 px-6 rounded-xl'
    }))
        

class SignupForm(UserCreationForm):
    class Meta:
        model =User
        fields =('username','email','password1','password2',)
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-3/4 py-4 px-6 rounded-xl'
    }))
    
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email address',
        'class': 'w-3/4 py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-3/4 py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat Password',
        'class': 'w-3/4 py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold = False)[0:48]
    categories = Category.objects.all()
    
    return render(request, 'core/index.html', {
        'categories': categories,
        'items' : items,
    })

def contact(request):
     return render(request, 'core/contact.html')
 

def signup(request):
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')  # Redirect to login or another page after successful signup
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
        })  # Make sure to return HttpResponse

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>  {% block title %}  {% endblock %} | Soko</title>
</head>
<body>
    {% load humanize %}
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 ">
        <a href="/" class="text-xl font-semibold">Soko</a>
        <div class="space-x-6">
         
            <a  href="{%url 'item:new'%}" class="text-lg font-semibold hover:text-gray-500 ">New Item</a>
         
            <a  href="{%url 'item:items'%}" class="text-lg font-semibold hover:text-gray-500 ">Browse</a>

            {%if request.user.is_authenticated%}
           
            <a  href="{%url 'conversation:inbox'%}" class="px-6 py-3 text-lg font-semibold rounded-xl bg-blue-300 hover:bg-blue-500 border-b border-blue-300 ">Inbox</a>
            <a  href="{%url 'dashboard:index'%}" class="px-6 py-3 text-lg font-semibold rounded-xl bg-blue-300 hover:bg-blue-500 border-b border-blue-300 ">Dashboard</a>

            {%else%}
            <a  href="{%url 'core:signup'%}" class="px-6 py-3 text-lg font-semibold rounded-xl bg-blue-300 hover:bg-blue-500 border-b border-blue-300 ">Sign up</a>
            <a  href="{%url 'core:login'%}" class="px-6 py-3 text-lg font-semibold rounded-xl bg-blue-300 hover:bg-blue-500 border-b border-blue-300 ">Login</a>
            {%endif%}



        </div>
        
    </nav>

    <div class="px-6 py-6">
     {% block content %}

     {% endblock %}
    </div>
    <br> 

    <footer class="py-6 px-6 flex justify-between items-center  bg-gray-400">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold " > About</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, accusamus id? Sapiente, tempora nesciunt, voluptas excepturi quam explicabo consequatur consectetur alias, necessitatibus laudantium in nemo iste vel cumque possimus illum.</p>

        </div>

        <div class="w-1/3 pr-10">  
            <h3 class="mb-5 font-semibold " > Menu</h3>  

                <ul> 
                   <li> <a  href="#" class="text-lg text-blue-500 font-semibold hover:text-gray-600 ">About</a></li>
                     <li><a  href="{%url 'core:contact'%}" class="text-lg text-blue-500 font-semibold hover:text-gray-600 ">Contact</a></li>
                    <li> <a  href="#" class="text-lg text-blue-500 font-semibold hover:text-gray-600 ">privacy policy</a></li>
                </ul> 

 
    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html'  %}

{% block title %} 
Contact

{% endblock %}

{% block content %}

<h1>call me</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html'  %}
{% load humanize %}

{% block title %} 
Welcome

{% endblock %}

{% block content %}

<!-- <div class="mt-6 px-6 py-12 bg-gray-300 rounded-xl">
    <h2 class="mb-12 text-2xl text-center "> Categories</h2>

    <div class="grid grid-cols-3  gap-3 ">
        {% for category in categories%}
            <div class="p-6 bg-white rounded-xl   hover:bg-blue-100  ">

                    <div >
                        <h3 class="text-xl">{{category.name}}</h3>
                        <p class="text-gray-500"> {{category.items.count}} Items </p>
                    </div>
                </a>
            </div>
        {%endfor%}
    </div> 
</div> -->

<div class="mt-6 px-6 py-12 bg-gray-300 rounded-xl">
    <h2 class="mb-12 text-2xl text-center "> Newest Items</h2>

    <div class="grid grid-cols-3  gap-3 ">
        {% for item in items%}
            <div class="p-6 bg-white rounded-xl   hover:bg-blue-100  ">
                <a href="{%url 'item:detail' item.id%}" >
                    <div >
                        <img src="{{item.image.url}}" >
                    </div>

                    <div >
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price: {{item.price|intcomma}}</p>
                    </div>
                </a>
            </div>
        {%endfor%}
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html'  %}

{% block title %} 
Login

{% endblock %}

{% block content %}

<div class="w-1/2  p-6 my-6 mx-auto bg-blue-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

       

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>

         
         <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{form.password}}
        </div>

         

        {%if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form%}
                    {{field.errors}}
               {%endfor%}
            

        {{ form.non_field_errors}}
    </div>
        {%endif%}

        <button type="submit" formmethod="post" class=" px-6 py-3 text-lg font-semibold rounded-xl bg-blue-300 hover:bg-blue-500 border-b border-blue-300">Login </button>

    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html'  %}

{% block title %} 
Sign up

{% endblock %}

{% block content %}

<div class="w-1/2  p-6 my-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p}}
        <button class=" px-6 py-3 text-lg font-semibold rounded-xl bg-blue-300 hover:bg-blue-500 border-b border-blue-300">Sign Up </button>

    </form>
</div>
{% endblock %}